In [5]:
import requests
import pandas as pd
from datetime import date

TOKEN = "629249a37423850587476dbd81dca910635fcf1df085430f80c788a09d34c9e8"

# Serie: Tasa objetivo
serie = "SF61745"

inicio = "1998-01-01"
fin = date.today().strftime("%Y-%m-%d")  # fecha de hoy en formato yyyy-mm-dd

url = f"https://www.banxico.org.mx/SieAPIRest/service/v1/series/{serie}/datos/{inicio}/{fin}"

headers = {"Bmx-Token": TOKEN}

response = requests.get(url, headers=headers)
print("Status:", response.status_code)

data = response.json()

# Extraer datos
datos = data["bmx"]["series"][0]["datos"]

df = pd.DataFrame(datos)
df.columns = ["fecha", "tasa_objetivo"]

# OJO: Banxico suele devolver fecha como dd/MM/yyyy dentro del JSON
df["fecha"] = pd.to_datetime(df["fecha"], format="%d/%m/%Y")
df["tasa_objetivo"] = pd.to_numeric(df["tasa_objetivo"], errors="coerce")

df = df.sort_values("fecha").reset_index(drop=True)

df.head()

Status: 200

       fecha  tasa_objetivo
0 2008-01-21            7.5
1 2008-01-22            7.5
2 2008-01-23            7.5
3 2008-01-24            7.5
4 2008-01-25            7.5

In [6]:
import requests
import pandas as pd
from datetime import date

TOKEN = "629249a37423850587476dbd81dca910635fcf1df085430f80c788a09d34c9e8"


serie = "SF60633"  # CETES 28 días

inicio = "1998-01-01"
fin = date.today().strftime("%Y-%m-%d")

url = f"https://www.banxico.org.mx/SieAPIRest/service/v1/series/{serie}/datos/{inicio}/{fin}"

headers = {"Bmx-Token": TOKEN}

response = requests.get(url, headers=headers)
print("Status:", response.status_code)

data = response.json()
datos = data["bmx"]["series"][0]["datos"]

df_cetes = pd.DataFrame(datos)
df_cetes.columns = ["fecha", "cetes_28"]

df_cetes["fecha"] = pd.to_datetime(df_cetes["fecha"], format="%d/%m/%Y")
df_cetes["cetes_28"] = pd.to_numeric(df_cetes["cetes_28"], errors="coerce")

df_cetes = df_cetes.sort_values("fecha").reset_index(drop=True)

df_cetes.head()

Status: 200

       fecha  cetes_28
0 2006-09-19      7.05
1 2006-09-26      7.05
2 2006-10-03      7.05
3 2006-10-10      7.06
4 2006-10-17      7.05

In [7]:
df_cetes["fecha"].min(), df_cetes["fecha"].max()

(Timestamp('2006-09-19 00:00:00'), Timestamp('2026-02-17 00:00:00'))

In [ ]:
df_cetes.to_csv("raw/cetes_28_banxico_diario.csv", index=False)